services:

  ghost:
    image: ghost:5-alpine
    ports:
      - "8080:2368"
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: Pedro2020a!
      database__connection__database: ghost
    volumes:
      - "ghost:/var/lib/ghost"
    networks:
      - public
      - private
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pedro2020a!
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - private


volumes:
  ghost:
  db:

networks:
  public:
  private: